# Generated by Django 3.2.4 on 2021-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='building',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
