# Generated by Django 3.2.4 on 2021-06-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center_app', '0002_auto_20210622_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ApartmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center_app.apartment', verbose_name='Идентификатор квартиры'),
        ),
    ]
