# Generated by Django 3.2.4 on 2021-06-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_app', '0004_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
