# Generated by Django 3.2.4 on 2021-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_app', '0005_contract_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
